filegroup(
    name = "bison_repository_ext_bzl",
    srcs = ["bison_repository_ext.bzl"],
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "bison_toolchains_ext_bzl",
    srcs = ["bison_toolchains_ext.bzl"],
    visibility = ["//:__subpackages__"],
)
