#define BITSIZEOF_PTRDIFF_T 64
#define BITSIZEOF_SIG_ATOMIC_T 32
#define BITSIZEOF_SIZE_T 64
#define BITSIZEOF_WCHAR_T 32
#define BITSIZEOF_WINT_T 32
#define CHECK_PRINTF_SAFE 1
#define DBL_EXPBIT0_BIT 20
#define DBL_EXPBIT0_WORD 1
#define FLT_EXPBIT0_BIT 23
#define FLT_EXPBIT0_WORD 0
#define GETTIMEOFDAY_TIMEZONE void
#define GNULIB_CLOSE_STREAM 1
#define GNULIB_DIRNAME 1
#define GNULIB_FD_SAFER_FLAG 1
#define GNULIB_FOPEN_SAFER 1
#define GNULIB_FSCANF 1
#define GNULIB_LOCK 1
#define GNULIB_MALLOC_GNU 1
#define GNULIB_MSVC_NOTHROW 1
#define GNULIB_PIPE2_SAFER 1
#define GNULIB_SCANF 1
#define GNULIB_SNPRINTF 1
#define GNULIB_STRERROR 1
#define GNULIB_STRERROR_R_POSIX 1
#define HAVE_ALLOCA 1
#define HAVE_ALLOCA_H 1
#define HAVE_CALLOC_POSIX 1
#define HAVE_CATGETS 1
#define HAVE_CFLOCALECOPYCURRENT 1
#define HAVE_CFLOCALECOPYPREFERREDLANGUAGES 1
#define HAVE_CFPREFERENCESCOPYAPPVALUE 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_CLOCK_SETTIME 1
#define HAVE_DECL_ALARM 1
#define HAVE_DECL_CLEARERR_UNLOCKED 1
#define HAVE_DECL_FEOF_UNLOCKED 1
#define HAVE_DECL_FERROR_UNLOCKED 1
#define HAVE_DECL_FFLUSH_UNLOCKED 0
#define HAVE_DECL_FGETS_UNLOCKED 0
#define HAVE_DECL_FPUTC_UNLOCKED 0
#define HAVE_DECL_FPUTS_UNLOCKED 0
#define HAVE_DECL_FREAD_UNLOCKED 0
#define HAVE_DECL_FWRITE_UNLOCKED 0
#define HAVE_DECL_GETCHAR_UNLOCKED 1
#define HAVE_DECL_GETC_UNLOCKED 1
#define HAVE_DECL_GETDTABLESIZE 1
#define HAVE_DECL_GETHRTIME 0
#define HAVE_DECL_MBSWIDTH_IN_WCHAR_H 0
#define HAVE_DECL_OBSTACK_PRINTF 0
#define HAVE_DECL_PROGRAM_INVOCATION_NAME 0
#define HAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME 0
#define HAVE_DECL_PUTCHAR_UNLOCKED 1
#define HAVE_DECL_PUTC_UNLOCKED 1
#define HAVE_DECL_SNPRINTF 1
#define HAVE_DECL_STRDUP 1
#define HAVE_DECL_STRERROR_R 1
#define HAVE_DECL_STRNDUP 1
#define HAVE_DECL_STRNLEN 1
#define HAVE_DECL_UNSETENV 1
#define HAVE_DECL_VSNPRINTF 1
#define HAVE_DECL_WCWIDTH 1
#define HAVE_DECL__SNPRINTF 0
#define HAVE_DECL___ARGV 0
#define HAVE_DUP2 1
#define HAVE_FCNTL 1
#define HAVE_FREXPL_IN_LIBC 1
#define HAVE_FREXP_IN_LIBC 1
#define HAVE_GETDTABLESIZE 1
#define HAVE_GETOPT_H 1
#define HAVE_GETOPT_LONG_ONLY 1
#define HAVE_GETPROGNAME 1
#define HAVE_GETRUSAGE 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_ICONV 1
#define HAVE_INTMAX_T 1
#define HAVE_INTTYPES_H 1
#define HAVE_INTTYPES_H_WITH_UINTMAX 1
#define HAVE_ISASCII 1
#define HAVE_ISNAND_IN_LIBC 1
#define HAVE_ISNANL_IN_LIBC 1
#define HAVE_ISWCNTRL 1
#define HAVE_LANGINFO_CODESET 1
#define HAVE_LDEXPL 1
#define HAVE_LDEXPL_IN_LIBC 1
#define HAVE_LDEXP_IN_LIBC 1
#define HAVE_LIMITS_H 1
#define HAVE_LOCALE_H 1
#define HAVE_LONG_LONG_INT 1
#define HAVE_LSTAT 1
#define HAVE_MALLOC_GNU 1
#define HAVE_MALLOC_POSIX 1
#define HAVE_MAP_ANONYMOUS 1
#define HAVE_MATH_H 1
#define HAVE_MBRTOWC 1
#define HAVE_MBSINIT 1
#define HAVE_MBSTATE_T 1
#define HAVE_MEMORY_H 1
#define HAVE_MINMAX_IN_SYS_PARAM_H 1
#define HAVE_MPROTECT 1
#define HAVE_NL_LANGINFO 1
#define HAVE_PIPE 1
#define HAVE_POSIX_SPAWN 1
#define HAVE_POSIX_SPAWNATTR_T 1
#define HAVE_POSIX_SPAWN_FILE_ACTIONS_T 1
#define HAVE_PTHREAD_MUTEX_RECURSIVE 1
#define HAVE_PTHREAD_RWLOCK 1
#define HAVE_PTHREAD_RWLOCK_RDLOCK_PREFER_WRITER 1
#define HAVE_RAISE 1
#define HAVE_REALLOC_POSIX 1
#define HAVE_SCHED_H 1
#define HAVE_SETLOCALE 1
#define HAVE_SIGACTION 1
#define HAVE_SIGALTSTACK 1
#define HAVE_SIGINTERRUPT 1
#define HAVE_SIGNED_SIG_ATOMIC_T 1
#define HAVE_SIGNED_WCHAR_T 1
#define HAVE_SIGNED_WINT_T 1
#define HAVE_SIGSET_T 1
#define HAVE_SIG_ATOMIC_T 1
#define HAVE_SNPRINTF 1
#define HAVE_SNPRINTF_RETVAL_C99 1
#define HAVE_SPAWN_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDINT_H_WITH_UINTMAX 1
#define HAVE_STDLIB_H 1
#define HAVE_STPCPY 1
#define HAVE_STRDUP 1
#define HAVE_STRERROR_R 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_STRNDUP 1
#define HAVE_STRNLEN 1
#define HAVE_STRUCT_SIGACTION_SA_SIGACTION 1
#define HAVE_STRUCT_STAT_ST_ATIMESPEC_TV_NSEC 1
#define HAVE_STRUCT_STAT_ST_BIRTHTIMESPEC_TV_NSEC 1
#define HAVE_STRUCT_TMS 1
#define HAVE_SYMLINK 1
#define HAVE_SYS_CDEFS_H 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_RESOURCE_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIMES_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_TOWLOWER 1
#define HAVE_UNISTD_H 1
#define HAVE_UNSETENV 1
#define HAVE_UNSIGNED_LONG_LONG_INT 1
#define HAVE_VAR___PROGNAME 1
#define HAVE_VSNPRINTF 1
#define HAVE_WAITID 1
#define HAVE_WCHAR_H 1
#define HAVE_WCHAR_T 1
#define HAVE_WCRTOMB 1
#define HAVE_WCSLEN 1
#define HAVE_WCSNLEN 1
#define HAVE_WCTYPE_H 1
#define HAVE_WCWIDTH 1
#define HAVE_WINT_T 1
#define HAVE_WORKING_O_NOATIME 0
#define HAVE_WORKING_O_NOFOLLOW 1
#define HAVE__BOOL 1
#define LDBL_EXPBIT0_BIT 0
#define LDBL_EXPBIT0_WORD 2
#define M4 "/usr/bin/m4"
#define M4_GNU_OPTION "--gnu"
#define MALLOC_0_IS_NONNULL 1
#ifndef __USE_MINGW_ANSI_STDIO
# define __USE_MINGW_ANSI_STDIO 1
#endif
#define NEED_PRINTF_DIRECTIVE_A 1
#define OPEN_TRAILING_SLASH_BUG 1
#define PROMOTED_MODE_T int
#define PTRDIFF_T_SUFFIX l
#define REPLACE_FPRINTF_POSIX 1
#define REPLACE_FUNC_STAT_FILE 1
#define REPLACE_PRINTF_POSIX 1
#define REPLACE_STRERROR_0 1
#define REPLACE_VFPRINTF_POSIX 1
#if defined __CYGWIN__
# define BOURNE_SHELL "sh"
#else
# define BOURNE_SHELL "/bin/sh"
#endif
#define SIG_ATOMIC_T_SUFFIX 
#ifndef SIZE_MAX
#endif
#define SIZE_T_SUFFIX ul
#define STDC_HEADERS 1
#define UNLINK_PARENT_BUG 1
#define USER_LABEL_PREFIX _
#define USE_POSIX_THREADS 1
#define USE_UNLOCKED_IO 1
#define WCHAR_T_SUFFIX 
#define WINT_T_SUFFIX 
#define YYTEXT_POINTER 1
#define __GETOPT_PREFIX rpl_

#include <gnulib_common_config.h>
#include <stdarg.h>

extern char **environ;

struct obstack;
int obstack_printf(struct obstack *obs, const char *format, ...);
int obstack_vprintf(struct obstack *obs, const char *format, va_list args);
int strverscmp(const char *s1, const char *s2);
