load("//bison:bison.bzl", "bison_toolchain_alias")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

bison_toolchain_alias(
    name = "toolchain",
    visibility = ["//visibility:public"],
)
