load("@rules_bison//bison/internal:toolchain.bzl", "bison_toolchain_alias")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

bison_toolchain_alias(
    name = "current_bison_toolchain",
    visibility = ["//visibility:public"],
)
